version: "3.8"
services:

  portfolio:
    container_name: portfolio
    build:
      context: .
    networks:
      - traefik
    environment:
      NODE_ENV: development
    labels:
      - "traefik.enable=true"

      - "traefik.http.services.portfolio.loadbalancer.server.port=80"

      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.rule=Host(`portfolio.anquetil.org`)"
      - "traefik.http.routers.portfolio.tls=true"
      - "traefik.http.routers.portfolio.tls.certresolver=letsencrypt"


networks:
  traefik:
    external: true