import '@/styles/globals.css'
import Head from 'next/head'
import { Roboto } from 'next/font/google'

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

export default function App({ Component, pageProps }) {
  return <main className={roboto.className}>
    <Head>
        <title>WIP - Julien Anquetil Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Component {...pageProps} />
  </main>
}
